### ISSUE TITLE
The example and/or explanatory text for the Remove operation can be clarified

### ISSUE THREAD

**Issue by smarts** [dharmafly/jsonpatch.com#47]
example object:

> ``` json
> {
>   "biscuits": [
>     {"name":"Digestive"},
>     {"name": "Choco Liebniz"}
>   ]
> }
> ```
> 
> **Remove**
> 
> ``` json
> {"op": "remove", "path": "/biscuits"}
> ```
> 
> Removes a value from an object or array.

Disclaimer: I apologize if I'm being stupid, but...
In my humble opinion the text doesn't clarify whether the example operation will remove the entire `biscuits` property (which would leave an empty object: `{}`) or if it will remove a single value from the `biscuits` array.

**Comment by almost** [comment]
I think you're correct and a an extra bit showing the result would be good. If you can make a PR I'll accept it.

**Comment by smarts** [comment]
I'm happy to do so if you can tell me what the actual behavior is in the scenario I listed.

**Comment by almost** [comment]
Yes of course! That op would remove the whole biscuits key so the result would be an empty object.
