### ISSUE TITLE
A better JSON Pointer

### ISSUE THREAD

**Issue by WebReflection** [dharmafly/jsonpatch.com#55]
I am pretty sure this is not the right channel but I couldn't find how to address this otherwise.

The [RFC6901](https://tools.ietf.org/html/rfc6901) specification looks very JSON-unfriendly, re-inventing arrays through escaped strings, easily error prone while manipulating any path in projects such [just-diff](https://github.com/angus-c/just#just-diff).

### A different proposal
A JSON pointer can be just an `Array` requiring zero special cases and granting type preservation.
Being an Array, a JSON pointer can be used also as generic JavaScript path pointer including the ability to have a `Symbol` as part of the key.

#### Examples
Given the following structure:
```js
{
  "biscuits": [
    { "name": "Digestive" },
    { "name": "Choco Leibniz" }
  ]
}
```
Instead of having `/biscuits/1/name` as path to point at `"Choco Leibniz"` string, the path could be `["biscuits", 1, "name"]`.

Since a path can be specified to use integers when it comes to `Array` access, it's now never ambiguous to understand the structure.

An object with numeric entries will have these represented as strings, an Array will have these represented as integers.

```js
{
  "biscuits": {
    "5": { "name": "Choco Leibniz" },
    "2": { "name": "Digestive" }
  }
}
```
Accordingly, to point at  `"Choco Leibniz"` we can now use `["biscuits", "5", "name"]`.

### Edge cases
Empty keys are allowed via `[""]` and at any level as in `["", 2, "", "name"]`.

#### Last item
Using the convention that an integer, if negative, means from the `Array` length, it is possible to point at a generic last item via `-1`, as example via `["biscuits", -1]`.

If the length of the array is meant, as appending at the end, being `length` an array property the path could simply be `["biscuits", "length"]`.

### Improvements
  * the pointer is a real JSON compatible structure itself, instead of a reinvented string with edge cases in core
  * humans can both easily read and write manually, if needed, paths, without needing to learn anything new
  * walking-through-the-path performances are better thanks to zero string manipulation needed and, in typed platforms, zero casting per object type needed too.

As typed array, JSON pointer would be a list/set that can contain either strings or integers.

As a wider solution, a JSON pointer could contain also JavaScript symbols which is a generic object key by all means, but this is out of current JSON Pointer scope/proposal.

Thanks in advance for any sort of outcome.

**Comment by almost** [comment]
Hi Andrea,

Thanks for message. I think you're right about the advantages of your method for pointing at elements. Unfortunately this repository is just an implementation of the RFC, we don't control the standard. I think that while the standard my not be perfect there is an advantage in having a standard, it means that you can interoperate with all the other JSONPatch implementations in loads of other languages.

As far as getting the standard changed I'm not sure where the best place to discuss that is. There used to be a mailing list but I can't find it anymore and maybe it's no longer running. You could try asking Paul Bryan (his email should be in the RFC document) but be prepared for the answer that they're not planning on doing another version soon.
