### ISSUE TITLE
JSON Patch Schema should have an "id"

### ISSUE THREAD

**Issue by gregsdennis** [dharmafly/jsonpatch.com#59]
If you're going to host the schema at http://json.schemastore.org/json-patch, it might be a good idea to add that URI as the `id` property so that it can be referenced by other schemata.

I've added this property into the Manatee.Json implementation.

**Comment by ThomasArdal** [comment]
The schema for JSON Patch is maintained in the https://github.com/SchemaStore/schemastore repository. If you believe it can be enhanced, please create a new issue in the repository. Thanks.
