### ISSUE TITLE
Path to array item without knowing index?

### ISSUE THREAD

**Issue by jdshkolnik** [dharmafly/jsonpatch.com#66]
Hi,

I looked through your spec but all the examples seemed to assume I know the position of an item in an array. Is there a way to specify the path to an array item based on one of its values?

```
[{
  "op": "replace",
  "path": "/model/dataSources/[name='item1']/connectionString",
  "value": "Data Source=something1;Initial Catalog=another1"
}]
```

for this:

```
{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "item1",
        "connectionString": "Data Source=source1;Initial Catalog=catalog1"
      },
      {
        "name": "item2",
        "connectionString": "Data Source=source2;Initial Catalog=catalog2"
      }
    ]
  }
}
```

**Comment by almost** [comment]
No, there's no way to do that with JSONPatch.

You could design a patch format that used JSONPath instead of JSONPointer and it would give you this, with the cost of being more complex overall.
