### ISSUE TITLE
[rfc] 

### ISSUE THREAD

**Issue by c4lliope** [dharmafly/jsonpatch.com#74]
Text of [request for comments, number 6902](https://tools.ietf.org/html/rfc6902)。

This issue subsumes #58 and #59, to suggest that each patch carry a timestamp
of the format `2019.07.22。07:22 pacific`, with varying-length segments to the left and right of the center 。divider.

This timestamp format would assist globally with synchronization efforts across devices.

For example, Redux-style interaction recording could be played back at real-time speeds, instead of the fixed-interval recordings that take place now:

https://drive.google.com/open?id=1idSfoVUs1mJmqONShOQ3IOuNFKWCbQ_2

If prefixed by an application-specific base64-encoded identifier, many applications can be simplified into streams of event logs.

**Comment by ThomasArdal** [comment]
Is this a request to change the schema for JSON Patch?
