### ISSUE TITLE
The status of this site

### ISSUE THREAD

**Issue by herkyl** [dharmafly/jsonpatch.com#79]
Hello @almost 👋 

What are the plans for the future of this site? I'm asking because it's the first answer of Google but many of the libraries are long outdated or deprecated. Do you have any plans on accepting the pull requests?

**Comment by ThomasArdal** [comment]
I'm currently trying to merge PRs and make improvements. I agree, the page showed up when I started searching for JSON Patch too. So, hoping to get this in a better state 👍
