### ISSUE TITLE
Escaping Number Strings as Keys

### ISSUE THREAD

**Issue by richam23bbc** [dharmafly/jsonpatch.com#9]
Using integers as keys for JSON hashes is relatively common and often outside of a developers' hands when using 3rd party APIs.

It would be great if there could be escape option to ensure if I do:
{"op": "add", "path": "/customers/23", "value": {"name": "Foo", "account" : "barred"}}
I would always generate something like
{
...
  "customers" : {
    "23" : {  "name" : "Foo", "account " : "barred"}
  }
...
}

And not:
{
...
  "customers" : [ null,null,null,..(19 nulls),..,{  "name" : "Foo", "account " : "barred"}]
...
}

Maybe using ~2 would be fine
So something like:
{"op": "add", "path": "/customers/~223", "value": {"name": "Foo", "account" : "barred"}}

**Comment by almost** [comment]
This is actually a question for the JSON Patch spec. This library merely tries to implement the spec correctly.

However, whether a section of a pointer refers to an array or to an object depends on _what is already there_ and not whether or not it looks like a number. So in your example it would depends whether the exsiting document was:

```
{
  "customers": {}
}
```

or:

```
{
  "customers": []
}
```

(if there was not a customers element then it would be an error to attempt to add something to it)
